name: Insecure GitHub Actions Workflow

on: push

jobs:
  insecure-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Run as Root (Bad Practice)
        run: |
          echo "Running as root..."
          whoami
      
      - name: Use Latest Tag (Bad Practice)
        run: docker run alpine:latest echo "Using latest tag"
